### ISSUE TITLE
Update stuff

### ISSUE THREAD

**Issue by Tameiki** [rootkiwi/an2linuxserver#14]
Hello, congratulations for this script.

A little question about the server side of AN2Linux.

On the client part, the update process will be proceed by the Google Play Store or by F-Droid (in my case), but on the server side, it's look like there are no update script for future versions of the .py file.

Am I missing something or how update the server-side when updates ?

Thx & Regards

**Comment by rootkiwi** [comment]
Hello, thanks!

For now you could do `git pull` or if you're using arch there is an AUR available.

Otherwise here is a little funny one liner that you can use to start `an2linuxserver.py` that will check if there is an update available, just change `/usr/bin/an2linuxserver.py` on both locations to the correct path ;)

```
python3 -c "exec('import hashlib,urllib.request\nprint(\'\\\nAN2Linux can be updated\\\n\') if hashlib.sha256(open(\'/usr/bin/an2linuxserver.py\', \'rb\').read()).digest() !=\
hashlib.sha256(urllib.request.urlopen(\'https://github.com/rootkiwi/an2linuxserver/raw/master/an2linuxserver.py\').read()).digest() else print(\'\\\nAN2Linux is up to date\\\n\')')"\
&& python3 /usr/bin/an2linuxserver.py
```

On a more serious note, I'm not sure what is the best solution for such a script/program like this.

Normally you would want to be available in the various package repositories but at this stage the best solution is probably to use git and do a `git pull`.

**Comment by ammgws** [comment]
I believe this can be closed now @rootkiwi as it is a packaging issue
