### ISSUE TITLE
Notifications no longer displayed.

### ISSUE THREAD

**Issue by thvasilo** [rootkiwi/an2linuxserver#22]
For some reason notifications have stopped appearing. What can I do to debug this?
Are there ways to find out what's happening on the device and server side when a notification is created on the phone?

I'm using the latest version of server and client, my setup is through Bluetooth, I'm trying to display the test notification from the client.

I've ensured the Bluetooth connection works otherwise, and the server is running as usual, but notifications are not displayed. I'm on Ubuntu 16.04 LTS.

**Comment by rootkiwi** [comment]
Hmm that's strange, does it work with wifi?
Have you tried to do a pair with bluetooth to see what happens?

There's really no debug options implemented unfortunately, only way is to run the code through android studio yourself.

I'm not sure what the problem is sorry, please let me know if you find something.

**Comment by thvasilo** [comment]
Today it started working again, no idea what was causing the trouble. I'll re-open this if the problem returns.
