### ISSUE TITLE
Cannot pair

### ISSUE THREAD

**Issue by CottonEaster** [rootkiwi/an2linuxserver#40]
EDITED: Sorry; again I've got things working.

**Comment by rootkiwi** [comment]
Okey great :)

**Comment by rootkiwi** [comment]
Yea the instructions might need some work. And also about firewall rules. Im open to suggestions and pull requests :)

I use the app "OpenVPN for Android" and with that app you can say to bypass the vpn for LAN connections and it works. So the problem with VPN on phone might depend on what type of VPN and what app is used. Otherwise it might try to connect to a local ip (if you are using that) through the VPN, which will not work.
